### PR TITLE
Add p5nimib + plausible analytics

### PR DESCRIPTION
**Pull request by pietroppeter**
- [x] add p5nimib module that can be used import from c backend
  - [x] add useP5 to add link to p5 cdn
- [x] add plausible analytics
- [ ] update examples

### CODE REVIEW

**Comment by Foldover** [comment]
Hey, cool to see so much activity here :) I'd love to hear about your plans @pietroppeter

**Comment by pietroppeter** [comment]
Hi! Sorry, I think this PR was added by mistake to your repo.

I had a look some time ago to your bindings to p5js and found they were not working with current nim, so I made a quick wrapper that worked https://pietroppeter.github.io/nblog/drafts/bouncing_ball_p5js.html and opened an issue: https://github.com/Foldover/nim-p5/issues/1 (this got closed automatically when I merged the PR that fixed it in my fork)

Then recently I wanted to work more with p5js, so I I forked it: https://github.com/pietroppeter/p5nim

There I made a few changes:
- fixed bindings
- improve api (e.g. template for draw and setup)
- create a documentation with examples (made with nimib, a library I created to publish html from nim code, see https://github.com/pietroppeter/nimib): https://pietroppeter.github.io/p5nim/
- with help from others also we are working on having a working instance model
- add helpers to use p5nim with nimib

The idea is to wrap more (e.g. p5sound), create more examples and improve also the api of using p5js in nim.
I have also started to use it these days for advent of code: https://pietroppeter.github.io/adventofnim/2022/day01.html#viz
And I am not the only one: https://hugogranstrom.com/AdventOfNim/2022/day2/

Since I am now basically creating a new version of this library and I am making many changes I decided to go towards a hard fork and I also renamed the library to p5nim (also because I like better this name). The plan is to release it on nimble as p5nim when it is a bit more cleaned up.

Hope you do not mind the fork, I am very grateful for the original bindings which were a great place to start with, thanks a lot! I am closing anyway the PR (it is very easy to open a PR by mistake to original repo when you are working on a fork, I did not realize I did).

If you have suggestion on p5nim or would like to have the fixes also here, happy to listen or open a PR here!

**Comment by Foldover** [comment]
That all sounds amazing! I don't mind at all the fork, it's great that someone has the time and passion to work on p5 bindings. In fact, I think my bindings should be removed from nimble so there is no confusion as to which library is working and up-to-date.

**Comment by pietroppeter** [comment]
Good to hear 🙂. When I make the  PR to add p5nim on nimble I will also add removal of nimp5 then, quoting you from here.

**Pull request closed without merging**
